name: Update Notion with Steam Data

on:
  schedule:
    - cron: "5 22,06,14 * * *"
  workflow_dispatch:
  push:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: update notion games
        env:
          STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
          STEAM_USER_ID: ${{ secrets.STEAM_USER_ID }}
          NOTION_DATABASE_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          include_played_free_games: ${{secrets.include_played_free_games}}
          enable_item_update: ${{secrets.enable_item_update}}
          enable_filter: ${{secrets.enable_filter}}
        run: python main.py
